name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages-deployment"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6

    - uses: dtolnay/rust-toolchain@stable
  
    - uses: Swatinem/rust-cache@v2
      with:
        add-job-id-key: false
        add-rust-environment-hash-key: false
        shared-key: "bedrock-rs-cache"
        cache-on-failure: false
        cache-all-crates: true

    - name: Generate Documentation
      run: cargo doc --no-deps --all-features

    - name: Configure Pages
      id: pages
      uses: actions/configure-pages@v6
      
    - name: Add Root
      run: |
        cd target/doc
        touch index.html
        echo "<meta http-equiv=\"refresh\" content=\"0; url=bedrock/index.html\">" > index.html

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: target/doc
    
  deploy:
    name: Deploy
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
